---
title: "ENAR 2021"
---

echnological advances have made many wearable devices available for use in large epidemiological cohorts, national biobanks, and clinical studies. The embedding of multiple sensors in wearable devices now allows for continuous tracking of physical activity, sleep, circadian rhythmicity, heart rate, blood glucose and many more to come. This multi-system real-time monitoring of human physiology and ambient environmental exposure is increasingly accompanied by connected smartphone apps that collect contextual information concerning the individual’s behavior including real-time self-reports of quality of sleep, mood, stress, etc. This opens up a tremendous opportunity for clinical and public health researchers to unveil previously hidden but pivotal physiological and behavioral signatures and relate them to disability and disease. Therefore, understanding and analysis of complex multilevel functional, non-functional, and intensive longitudinal data produced by such devices becomes crucial.

This course will consist of three parts. First, we will present an overview of the functional data analysis methods for modeling physical activity data, review their strengths and limitations, and demonstrate their implementation in R packages refund and mgcv. Second, we cover a few popular non-functional approaches for extracting informative and interpretable features from wearable data. Third, we will overview intensive longitudinal methods for modelling data coming from electronic diaries and real-time smartphone surveys. We will demonstrate all the methods using epidemiological studies such as [Head Start Program](https://journals.lww.com/acsm-msse/fulltext/2016/09000/New_Insights_into_Activity_Patterns_in_Children,.11.aspx) and [National Health and Nutrition Examination Survey](https://link.springer.com/article/10.1007/s12561-018-09229-9) and a clinical study of [Congestive Heart Failure](https://www.tandfonline.com/doi/full/10.1080/01621459.2018.1482750).

This page contains materials by [Vadim Zipunnikov](http://www.biostat.jhsph.edu/~vzipunni/) and [Jeff Goldsmith](http://jeffgoldsmith.com) for the ENAR 2021 short course titled "Functional and Intensive Longitudinal Data Analysis for Wearables, Electronic Diaries, and Real-time Smartphone Surveys".
